[package]
name = "sway-clock"
version = "0.1.0"
authors = ["stephan"]
edition = "2021"

[dependencies]
chrono = "0.4"

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
# strip = "symbols" <- only in nightly
